### ISSUE TITLE
change background of signup page

### ISSUE THREAD

**Issue by gschandrasekhar** [chandug25/Blogwebsite#1]
i want to changr bg of sign up page to any attractive color

**Comment by AdarshKannarath** [comment]
Please Assign it to me

**Comment by Fahass** [comment]
Can I work on this issue?

**Comment by AdarshKannarath** [comment]
Hello @chandug25.
Should I add a more attractive background image or a solid color?

**Comment by sivaguttikonda** [comment]
Attractive color , and please change the form layout , and a vibrant color to form, @AdarshKannarath

**Comment by AdarshKannarath** [comment]
Sure.
I will make the changes as requested.

**Comment by AdarshKannarath** [comment]
![Screenshot 2023-10-20 220055](https://github.com/chandug25/Blogwebsite/assets/100022179/508ff99f-a1fe-442c-ae4c-dde4d2fc44d3)

Hello. How is this?
Give me your opinion!

**Comment by AdarshKannarath** [comment]
Can you please tell me if you are satisfied with the colors and layout so that I can make a PR!!

**Comment by sivaguttikonda** [comment]
please change signup color and change the font

**Comment by AdarshKannarath** [comment]
![Screenshot 2023-10-22 133041](https://github.com/chandug25/Blogwebsite/assets/100022179/398af778-35c3-4e0d-be93-98700e05ab11)

I took a minimalistic approach this time.
As you asked for, I changed the font.

**Comment by AdarshKannarath** [comment]
To make it more attractive I have added box shadow and border.

**Comment by AdarshKannarath** [comment]
Hello @chandug25.
Please respond to the PR.

**Comment by sivaguttikonda** [comment]
yeah, It looks better, merging your pr

**Comment by sivaguttikonda** [comment]
please make a pr again, @AdarshKannarath

**Comment by AdarshKannarath** [comment]
Hello.
I have a humble request.
Can you please check with the "hactoberfest" label?
Can you please try adding a "hactoberfest-accepted" label before merging?

**Comment by sivaguttikonda** [comment]
Please make a fresh pr and pull it. 
And later i will merge it. 
Last time the issue got closed automatically, so ur PR was deleted unexpectedly. 
So sorry for the inconvenience

**Comment by sivaguttikonda** [comment]
@AdarshKannarath

**Comment by AdarshKannarath** [comment]
No problem.
@chandug25 I have made a fresh PR.
Please try adding "hacktoberfest-accepted" label.

**Comment by AdarshKannarath** [comment]
![Screenshot 2023-10-25 172439](https://github.com/chandug25/Blogwebsite/assets/100022179/dfd110e8-f153-494f-a9af-e6f8908f0c54)

@chandug25 
Please try resolving this problem.
I am sorry if I am asking too much.
Thank You.

**Comment by sivaguttikonda** [comment]
please wait for
 few minutes , hope it will update soon

**Comment by AdarshKannarath** [comment]
> please wait for few minutes , hope it will update soon

It has been updated.
Thank You.
