### ISSUE TITLE
Contact Form Styling

### ISSUE THREAD

**Issue by gschandrasekhar** [chandug25/Blogwebsite#32]
Improve the styling of the contact form to make it more user-friendly and visually appealing.

**Comment by harshvyas-22** [comment]
I would love to contribute please assign to me

**Comment by harshvyas-22** [comment]
Can i change the background image?

**Comment by harshvyas-22** [comment]
made new contact page closes #32

**Comment by sivaguttikonda** [comment]
please create a PR. @harshvyas-22
