### ISSUE TITLE
Implement a Light/Dark Mode Toggle

### ISSUE THREAD

**Issue by gschandrasekhar** [chandug25/Blogwebsite#44]
Allow users to switch between light and dark modes with a JavaScript toggle button for improved accessibility and customization.

**Comment by Rachit1313** [comment]
Can you assign me?

**Comment by sivaguttikonda** [comment]
done @Rachit1313

**Comment by Bishwajitpvt** [comment]
hey @chandug25  can you assign this issue to me

**Comment by Bishwajitpvt** [comment]
implemented Light/Dark Mode Toggle,  can you check the  PR

**Comment by Bishwajitpvt** [comment]
**Light mode**
![image](https://github.com/chandug25/Blogwebsite/assets/77453811/07edfc17-1d10-448a-bed3-fe93c587b730)

**Dark mode**
![image](https://github.com/chandug25/Blogwebsite/assets/77453811/c0c2638f-b048-45ed-a057-c3f986d2dde2)
